### ISSUE TITLE
About running time reported in the paper

### ISSUE THREAD

**Issue by waghmaregovind** [mks0601/3DMPPE_POSENET_RELEASE#39]
Greetings,
In supplementary material of the paper, Table 8 shows running time for each component. My question is specifically about inference time of RootNet and PoseNet. As RootNet and PoseNet work on bounding boxes, is _frame_ same as that of _bounding box_ in this context? I think the numbers reported are with respect to per bounding box and not per image as single image can contain multiple people.

I'm providing two examples to clarify it further.

1. Consider an image with 1 person in it. So total time will be 0.141 s.
2. Consider an image with 3 people in it. So, as per my understanding, DetectNet will take 0.12 s, RootNet will take 3 x 0.01 s = 0.03 s and PoseNet will take 3 x 0.011 = 0.033 s. So, total time for this image is 0.12+0.03+0.033 = 0.183 s
-is this understanding correct?

Thanks for releasing the source.

**Comment by mks0601** [comment]
Hi, sorry for unclear description about the table.
As you said, the running times of RootNet and PoseNet are calculated for each bounding box.

However, the running time of them are not exactly proportional to the number of boxes in the image because of parallel processing.
One can make mini-batch with all bounding boxes of an image and fed the mini-batch to the models.

I checked that in case of the PoseNet, processing 8 boxes in parallel takes 3 times more time than that of processing 1 box
In case of RootNet, processing 8 boxes in parallel takes 2 times more time than that of processing 1 box.

Hope this can clarify your question.

**Comment by waghmaregovind** [comment]
Your response does clarify the issue. As you pointed out, example 2 given by me does not consider parallel processing and should be considered with respect to batch. Thanks for the prompt response and additional run time evaluations.
