### ISSUE TITLE
Some questions about the training data

### ISSUE THREAD

**Issue by GUO-W** [mks0601/3DMPPE_POSENET_RELEASE#49]
Hello, thank you very much for your excellent work and code!
I would like to ask that have you retrained the LCR model and single-shot model with the same traing data of 3DMPPE-posenet, or you just use the reported results of these papers on MuPoTS for the comparison?  
Besides, I'd like to ask that have you tried to train just on MuCo and test on MuPoTS, and what is the result? How much does the single person dataset(H3.6M) and 2D pose dataset(COCO, MPII) help the training?
Thanks again!

**Comment by mks0601** [comment]
Hi, sorry for late reply.

1. I haven't trained the LCR and single-shot model on the same training data because as I remember, training code of single-shot is not released. I just reported the numbers in their papers.

2. I haven't, but I think the effect of the in-the-wild dataset (even it only contains 2D pose annotations) is significant. Although there is random background augmentation in MuCo dataset, the diversity of the subject is very limited.

**Comment by GUO-W** [comment]
OK, I see. Thanks a lot for your reply!
