### ISSUE TITLE
If I use only two GPUs for training, Can it be worse training than original training?

### ISSUE THREAD

**Issue by kdh4672** [mks0601/3DMPPE_POSENET_RELEASE#85]
To the best of my knowledge about this module, If I code on train.py like:

`gpu_ids = 0,1`,
`batch_size = 32`

Then it works like `batch_size = 64` (Is it right?)

But in your paper, batch_size = 128, and used 4 GPU.

So I'm worried that It(two GPUs, batch_size=32) can make a difference with the original training.

So what should I do, If I want to train like your original paper with only two GPUs?

**Comment by mks0601** [comment]
I don't think there gonna be much difference.

**Comment by kdh4672** [comment]
Oh really? 
Then are you agree that If I use 2GPUs with these codes, It works like training with batch_size 64?:
```
gpu_ids = 0,1,
batch_size = 32
``'

**Comment by mks0601** [comment]
Yes. 

It seems you asked bunch of questions recently.
I'd like to say that asking some difficulties after checking your questions on your side would be much more beneficial for you to strengthen your implementation/research power (and also for me because I cannot answer all of your questions).
Also, giving some thank you messages when you got answers (especially when asking bunch of questions) can relieve some tiresome of answerers.

**Comment by kdh4672** [comment]
Oh Sorry..  I'm a github beginner, So I was not familiar for github culture... 
I will follow your advice, Thank you Dr.Moon

**Comment by mks0601** [comment]
I had no offensive meanings. Sorry if it sounds like that and ask me if you have further questions.
Good luck!
